//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentPositionTable
    {
        public int DepartmentPos_Id { get; set; }
        public string Department_Name { get; set; }
        public System.Guid DepartmentPos_Identifier { get; set; }
    }
}
