//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldInfoTable
    {
        public int FieldInfo_Id { get; set; }
        public string Update_Type { get; set; }
        public string Update_Text { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    }
}
