//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRTable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string IC { get; set; }
        public int Job_ID { get; set; }
        public int Department_ID { get; set; }
        public byte[] ProfilePicture { get; set; }
    
        public virtual DepartmentTable DepartmentTable { get; set; }
        public virtual JobTable JobTable { get; set; }
    }
}
